USE DATABASE SNOWFLAKE_SAMPLE_DATA;
DESC TABLE TPCDS_SF100TCL.STORE_SALES;

SELECT COUNT(*)
FROM TPCDS_SF100TCL.STORE_SALES;

USE WAREHOUSE COMPUTE_WH;
USE DATABASE SNOWFLAKE_LEARNING_DB;
CREATE SCHEMA IF NOT EXISTS BRONZE;

CREATE OR REPLACE TABLE BRONZE.STORE_SALES_RAM AS 
SELECT *
FROM SNOWFLAKE_SAMPLE_DATA.TPCDS_SF100TCL.STORE_SALES
LIMIT 50000000;